version: '3.8'
services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    ports:
      - "1433:1433"   
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Daniel123!"
      ACCEPT_EULA: "Y"
